---
# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  format:
    desc: Recursively format all Go files
    cmds:
      - go fmt ./...

  compile:
    desc: Builds GoGo with version information and readies for release
    cmds:
      - go run cmd/gogo/main.go CompileGo cmd/gogo . gogo darwin arm64

  compile:gadgets:
    desc: Builds the .gogo folder main.gogo.go file.
    cmds:
      - go run cmd/gogo/main.go build --gen-only

  install:
    desc: Installs gogo. This currently only works on arm64/macs, but will be updated soon.
    env:
      GOGO_KEEP_ARTIFACTS: true
      GOGO_VERBOSE: true
      GOGO_DISABLE_CACHE: true
    cmds:
      - |
        target=$(go env GOBIN)
        go run cmd/gogo/main.go gadget CompileGo --binaryName=gogo --inputFolderPath=./cmd/gogo --outputFolderPath=/tmp --tags=gogo --strArch="arm64" --strOs="darwin" --versionPath="github.com/2bit-software/gogo/cmd/gogo/cmds"
        echo "Copying gogo to ${target}"
        cp /tmp/gogo-darwin-arm64 ${target}/gogo

  install:wizard:
    desc: Install Wizard, the mage drop-in replacement.
    env:
      GOGO_KEEP_ARTIFACTS: true
      GOGO_VERBOSE: true
      GOGO_DISABLE_CACHE: true
    cmds:
      - |
        target=$(go env GOBIN)
        go run cmd/gogo/main.go gadget CompileGo --binaryName=wizard --inputFolderPath=./cmd/wizard --outputFolderPath=/tmp --tags=gogo --strArch="arm64" --strOs="darwin" --versionPath="github.com/2bit-software/gogo/cmd/gogo/cmds"
        echo "Copying wizard to ${target}"
        cp /tmp/wizard-darwin-arm64 ${target}/wizard

  test:
    desc: Runs all tests
    cmds:
      - go test ./...

  test:update-snapshots:
    desc: Runs all tests and updates the snapshots. Use this sparingly, and confirm the results!
    env:
      UPDATE_SNAPSHOTS: true
    cmds:
      - go test ./...

  check:
    desc: Runs all linters/checks/validations against all files
    preconditions:
      - command -v pre-commit
    cmds:
      - pre-commit run --all-files
      - pre-commit run --hook-stage push --all-files
